---
talk-title: " MESSI-benchmark"
talk-subtitle: "Multiomics Experiments with SyStematic Interrogation"
talk-descrip: "A pipeline for benchmarking multi-omics integration methods on classification problems using Nextflow"
author: "Chunqing Tony Liang"
other-authors: "Dr. Amrit Singh"
talk-date: "March 7, 2024"
format: revealjs
---

<!-- Title slide edit from other slide -->

{{< include _titleslide.qmd >}}


## Multiomics Integration and Existing problem

Profiling of different molecular measurements (i.e. genes, proteins, metabolites) from same biological samples.


<!--- Change color for this --->
::: {.callout-tip}

# Motivation

- Multiomics is a new emerging field of study --> How to levarage it?

- Many integration methods --> Which to use and under what circumstances?
<!-- - "Gap" between biologists and computer-based multiomics methods. -->

- Reproducibility crisis --> How to reproduce method and get reliable results?

:::

<!---- 

Fix this point of solution, make a more concrete and summarized 
note point for audiences

Make incremental as  well
---->

::: {.fragment .incremental}

Solutions:

- Test many methods at the same time

- Make pipeline to follow sames steps just like a "protocol"

- Report relevant metrics (like those of binary classification)

:::

<!-- ::: {.callout-note}

# How to leverage multiple modalities?

...

::: -->

<!-- ::: {.callout-note}

- Which method to choose? 
- How to interpret the results?
- How to reproduce these and present to your labmates?

::: -->


## Overview of MESSI-benchmark

::: {.callout-note}

This slide should have the figure for what is doing of the pipeline


- This is the space for the figure?

- ...

- ...

- ...

- ...

- ...


:::


:::: {.columns .fragment .f3}

::: {.column width="48%"}

- Generalizable for more integration methods

- Data transformable for Python or R based methods

- Reproducible workflow, no more fail to reproduce research

:::

::: {.column width="12%"}

:::

::: {.column width="40%"}

- Setup easily through nf-core^[@ewels2020nf]

- Help to develop new integration method

- Compare large set of independent data at once




:::

::::
## Progress, results, and future directions

::: {.callout-note}

This slide could have what have found now or expected to find


:::

## {.smaller}

### Acknowledgements

:::: {.columns}

::: {.column width="50%"}


- [Dr. Amrit Singh]{.bold}
- Dr. Young Woong Kim
- Dr. Maryam Ahmadzadeh
- Rishika Daswani
- Roy He
- Michael Yoon
- Jeffrey Tang
- Akshdeep Sandhu
- Yovindu Don
- Raam Sivakumar
- Prabhleen Sandhu
- Mingming Zhang
- Samuel Leung

:::
::: {.column width="50%"}

Another thing goes here maybe, like lab pic

:::

::::

## References